---
core:
    num_workers: 10


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/home/wkwiatjr2/ospfv2Config/hosts.yaml"
        group_file: "/home/wkwiatjr2/ospfv2Config/groups.yaml"
        defaults_file: "/home/wkwiatjr2/ospfv2Config/defaults.yaml"
