---
R1:
    hostname: 172.29.129.11
    platform: 'ios'
    username: wayne
    password: cisco
    groups:
        - cisco_group

R2:
    hostname: 172.29.129.12
    platform: 'ios'
    username: wayne
    password: cisco
    groups:
        - cisco_group

R3:
    hostname: 172.29.129.13
    platform: 'ios'
    username: wayne
    password: cisco
    groups:
        - cisco_group


R4:
    hostname: 172.29.129.14
    platform: 'ios'
    username: wayne
    password: cisco
    groups:
        - cisco_group


R5:
    hostname: 172.29.129.15
    platform: 'ios'
    username: wayne
    password: cisco
    groups:
        - cisco_group


R6:
    hostname: 172.29.129.16
    platform: 'ios'
    username: wayne
    password: cisco
    groups:
        - cisco_group


R7:
    hostname: 172.29.129.17
    platform: 'ios'
    username: wayne
    password: cisco
    groups:
        - cisco_group

R8:
    hostname: 172.29.129.18
    platform: 'ios'
    username: wayne
    password: cisco
    groups:
        - cisco_group