---


R1:
    hostname: 172.29.129.11
    groups:
        - cisco_group
    data:
        domain: kwiatriot

R2:
    hostname: 172.29.129.12
    groups:
        - cisco_group
    data:
        domain: kwiatriot


R3:
    hostname: 172.29.129.13
    groups:
        - cisco_group
    data:
        domain: kwiatriot


R4:
    hostname: 172.29.129.14
    groups:
        - cisco_group
    data:
        domain: kwiatriot


R5:
    hostname: 172.29.129.15
    groups:
        - cisco_group
    data:
        domain: kwiatriot


R6:
    hostname: 172.29.129.16
    groups:
        - cisco_group
    data:
        domain: kwiatriot


R7:
    hostname: 172.29.129.17
    groups:
        - cisco_group
    data:
        domain: kwiatriot


R8:
    hostname: 172.29.129.18
    groups:
        - cisco_group
    data:
        domain: kwiatriot
