---

SWITCHPORT:
    interfaces:
        g0/0:
            switchport: enabled
            ipaddr: 
            description: Trunk to D1
        g0/1:
            switchport: enabled
            ipaddr: 
            description: Trunk to D2
        g0/2:
            switchport: enabled
            ipaddr: 
            description: Access to VLAN 10
        loop0:
            switchport: enabled
            ipaddr: 6.6.6.6 255.255.255.255
            description: Loopback

Trunked:
    trunk:
        interfaces:
            gig0/0:
                allowed_vlans: 10,20,30,40,99
                native: 99
            gig0/1:
                allowed_vlans: 10,20,30,40,99
                native: 99

VLAN:
  - number: 10
    name: TEN
  - number: 20
    name: TWENTY
  - number: 30
    name: THIRTY
  - number: 40
    name: FORTY
  - number: 99
    name: NATIVE

