---
# ISIS:
#     nsap: 49.0001.0000.0000.0003.00
#     level: level-1-2
#     interfaces:
#         g0/1:
#             sub_iface: g0/1.10
#             encapsulation: dot1q 10
#         g0/2:
#             sub_iface: g0/2.10
#             encapsulation: dot1q 10
#         loo0:
#             ipaddr: 3.3.3.3 255.255.255.255


Etherchannel:
    interfaces:
        - gigabitEthernet0/2
        - gigabitEthernet0/3
    group: 1
    protocol: active

Trunked:
    trunk:
        interfaces:
            gig1/0:
                allowed_vlans: 10,20,30,40,99
                native: 99
            gig1/1:
                allowed_vlans: 10,20,30,40,99
                native: 99
            gig1/2:
                allowed_vlans: 10,20,30,40,99
                native: 99
            gig1/3:
                allowed_vlans: 10,20,30,40,99
                native: 99

SWITCHPORT:
    interfaces:
        g0/0:
            switchport: disabled
            ipaddr: 10.1.1.10 255.255.255.252
            description: To C1
        g0/1:
            switchport: disabled
            ipaddr: 10.1.1.18 255.255.255.252
            description: To C2
        vlan10:
            switchport: enabled
            ipaddr: 10.1.10.2 255.255.255.0
            description: 
        vlan20:
            switchport: enabled
            ipaddr: 10.1.20.2 255.255.255.0
            description:
        vlan30:
            switchport: enabled
            ipaddr: 10.1.30.2 255.255.255.0
            description:
        vlan40:
            switchport: enabled
            ipaddr: 10.1.40.2 255.255.255.0
            description:
        vlan99:
            switchport: enabled
            ipaddr: 10.1.99.2 255.255.255.0
            description:
        
VLAN:
  - number: 10
    name: TEN
  - number: 20
    name: TWENTY
  - number: 30
    name: THIRTY
  - number: 40
    name: FORTY
  - number: 99
    name: NATIVE
