---
# ISIS:
#     nsap: 49.0001.0000.0000.0004.00
#     level: level-1-2
#     interfaces:
#         g0/1:
#             sub_iface: g0/1.10
#             encapsulation: dot1q 10
#         g0/2:
#             sub_iface: g0/2.10
#             encapsulation: dot1q 10
#         loo0:
#             ipaddr: 4.4.4.4 255.255.255.255


Etherchannel:
    interfaces:
        - gigabitEthernet0/2
        - gigabitEthernet0/3
    group: 1
    protocol: active

SWITCHPORT:
    interfaces:
        g0/0:
            switchport: disabled
            ipaddr: 10.1.1.14 255.255.255.252
            description: To C1
        g0/1:
            switchport: disabled
            ipaddr: 10.1.1.22 255.255.255.252
            description: To C2
        vlan10:
            ipaddr: 10.1.10.1 255.255.255.0
        vlan20:
            ipaddr: 10.1.20.1 255.255.255.0
        vlan30:
            ipaddr: 10.1.30.1 255.255.255.0
        vlan40:
            ipaddr: 10.1.40.1 255.255.255.0
        vlan99:
            ipaddr: 10.1.99.1 255.255.255.0

Trunked:
    trunk:
        interfaces:
            gig1/0:
                allowed_vlans: 10,20,30,40,99
                native: 99
            gig1/1:
                allowed_vlans: 10,20,30,40,99
                native: 99
            gig1/2:
                allowed_vlans: 10,20,30,40,99
                native: 99
            gig1/3:
                allowed_vlans: 10,20,30,40,99
                native: 99


VLAN:
  - number: 10
    name: TEN
  - number: 20
    name: TWENTY
  - number: 30
    name: THIRTY
  - number: 40
    name: FORTY
  - number: 99
    name: NATIVE
