---
core:
    num_workers: 100


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/home/wkwiatjr2/Nornir/hosts.yaml"
        group_file: "/home/wkwiatjr2/Nornir/groups.yaml"
        defaults_file: "/home/wkwiatjr2/Nornir/defaults.yaml"
